think_ahead:
  60  # The amount of seconds to simulate a vehicle's path to check if it intersects with the boundaries
lat_lon_packet_age_max: 10 # The maximum age of a latitude packet used to calculate the speed (This should be fine)
home: # Home lat/long point
  lat: 35.7270309
  lon: -78.695587
decimation_factor: 15 # This is, essentially, how much data to store to the database. If this is 0, only the closest will be stored, but otherwise every nth unique set of information will be stored to the db.
decimation_force_new_data: true
utc_time_offset: -4 # the time offset in hours
remember: 60 # maximum time in seconds where the aircraft has not sent a packet for the system to track it
dump1090_dir: './dump1090' # the storage location of https://github.com/flightaware/dump1090 or https://github.com/mutability/dump978
json_speed: 0  # time between updates
min_trip_length: 90 # the minimum time a plane must be seen to be saved to mongod (sec)
print_top_planes: 25 # the number of closest planes to print in normal mode
mongo_address: "127.0.0.1:27017"
kafka_address: "" # The address for the KAFKA server
filters:
  close: [10, 1000] # write filters here with the format [dist(km), alt(m)]
  tooclose: [5, 1000]